export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL_ACCOUNT = 'LOGIN_FAIL_ACCOUNT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

